### ISSUE TITLE
Trainning EOFError

### ISSUE THREAD

**Issue by AeolianLbells** [alexfrom0815/Online-3D-BPP-PCT#20]
Hi,

The error info ：

Time version: holder80-2023.02.16-08-34-57 is training
Updates 20, num timesteps 6720, FPS 50
Last 10 training episodes: mean/median reward 2.9/2.9, min/max reward 1.3/4.1
The dist entropy 3.71353, the value loss 1.83093, the action loss -0.72693
The mean space ratio is 0.2870839419642857, the ratio threshold is0.4147317857142857

Process ForkProcess-39:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/content/Online-3D-BPP-PCT/wrapper/shmem_vec_env.py", line 143, in _subproc_worker
    obs, reward, done, info = env.step(data)
  File "/content/Online-3D-BPP-PCT/wrapper/monitor.py", line 54, in step
    ob, rew, done, info = self.env.step(action)
  File "/content/Online-3D-BPP-PCT/pct_envs/PctDiscrete0/bin3D.py", line 163, in step
    succeeded = self.space.drop_box(next_box, idx, rotation_flag, self.next_den, self.setting)
  File "/content/Online-3D-BPP-PCT/pct_envs/PctDiscrete0/space.py", line 385, in drop_box
    self.box_vec[self.box_idx] = np.array(
IndexError: index 80 is out of bounds for axis 0 with size 80
Traceback (most recent call last):
  File "main.py", line 61, in <module>
    main(args)
  File "main.py", line 56, in main
    trainTool.train_n_steps(envs, args, device)
  File "/content/Online-3D-BPP-PCT/train_tools.py", line 67, in train_n_steps
    obs, reward, done, infos = envs.step(selected_leaf_node.cpu().numpy())
  File "/content/Online-3D-BPP-PCT/wrapper/vec_env.py", line 108, in step
    return self.step_wait()
  File "/content/Online-3D-BPP-PCT/envs.py", line 179, in step_wait
    obs, reward, done, info = self.venv.step_wait()
  File "/content/Online-3D-BPP-PCT/wrapper/shmem_vec_env.py", line 80, in step_wait
    outs = [pipe.recv() for pipe in self.parent_pipes]
  File "/content/Online-3D-BPP-PCT/wrapper/shmem_vec_env.py", line 80, in <listcomp>
    outs = [pipe.recv() for pipe in self.parent_pipes]
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError

It trains for 2 epochs then the error raise up. 
My environment is under Colab.  python=3.8  torch=1.13.1+cu116  gym= 0.13.0
And my container size is [2800,800,180], givenData.py likes:

import pandas as pd
container_size = [2800,800,180]

item_size_set = []

medf=pd.read_csv('metadata.csv',index_col=0)
num=medf.to_numpy(dtype=int)
lisg=num.tolist()

for i in range(len(lisg)):
     tup=tuple(lisg[i])
     item_size_set.append(tup)

those items data is not continuons, likes:
(306,96,18)
(1069,814,18)
(669,266,18)...

Do you have any ideas for this error? Thanks in advance.

**Comment by AeolianLbells** [comment]
those items data is not continue, likes:
(306,96,18)
(1069,814,18)
(669,266,18)...
