### ISSUE TITLE
AttributeError: 'PackingDiscrete' object has no attribute 'action_space'

### ISSUE THREAD

**Issue by luzhenyv** [alexfrom0815/Online-3D-BPP-PCT#8]
Dear Sir

I ran Quick start, typing in "python main.py", but I got the error: 

/home/steven/Online-3D-BPP-PCT-main/attention_model.py:9: DeprecationWarning: __class__ not set defining 'AttentionModelFixed' as <class 'attention_model.AttentionModelFixed'>. Was __classcell__ propagated to type.__new__?
  class AttentionModelFixed(NamedTuple):
/home/steven/Online-3D-BPP-PCT-main/wrapper/shmem_vec_env.py:17: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.bool: ctypes.c_bool}
Please input the experiment name
demo
[(1, 1, 1), (1, 1, 2), (1, 1, 3), (1, 1, 4), (1, 1, 5), (1, 2, 1), (1, 2, 2), (1, 2, 3), (1, 2, 4), (1, 2, 5), (1, 3, 1), (1, 3, 2), (1, 3, 3), (1, 3, 4), (1, 3, 5), (1, 4, 1), (1, 4, 2), (1, 4, 3), (1, 4, 4), (1, 4, 5), (1, 5, 1), (1, 5, 2), (1, 5, 3), (1, 5, 4), (1, 5, 5), (2, 1, 1), (2, 1, 2), (2, 1, 3), (2, 1, 4), (2, 1, 5), (2, 2, 1), (2, 2, 2), (2, 2, 3), (2, 2, 4), (2, 2, 5), (2, 3, 1), (2, 3, 2), (2, 3, 3), (2, 3, 4), (2, 3, 5), (2, 4, 1), (2, 4, 2), (2, 4, 3), (2, 4, 4), (2, 4, 5), (2, 5, 1), (2, 5, 2), (2, 5, 3), (2, 5, 4), (2, 5, 5), (3, 1, 1), (3, 1, 2), (3, 1, 3), (3, 1, 4), (3, 1, 5), (3, 2, 1), (3, 2, 2), (3, 2, 3), (3, 2, 4), (3, 2, 5), (3, 3, 1), (3, 3, 2), (3, 3, 3), (3, 3, 4), (3, 3, 5), (3, 4, 1), (3, 4, 2), (3, 4, 3), (3, 4, 4), (3, 4, 5), (3, 5, 1), (3, 5, 2), (3, 5, 3), (3, 5, 4), (3, 5, 5), (4, 1, 1), (4, 1, 2), (4, 1, 3), (4, 1, 4), (4, 1, 5), (4, 2, 1), (4, 2, 2), (4, 2, 3), (4, 2, 4), (4, 2, 5), (4, 3, 1), (4, 3, 2), (4, 3, 3), (4, 3, 4), (4, 3, 5), (4, 4, 1), (4, 4, 2), (4, 4, 3), (4, 4, 4), (4, 4, 5), (4, 5, 1), (4, 5, 2), (4, 5, 3), (4, 5, 4), (4, 5, 5), (5, 1, 1), (5, 1, 2), (5, 1, 3), (5, 1, 4), (5, 1, 5), (5, 2, 1), (5, 2, 2), (5, 2, 3), (5, 2, 4), (5, 2, 5), (5, 3, 1), (5, 3, 2), (5, 3, 3), (5, 3, 4), (5, 3, 5), (5, 4, 1), (5, 4, 2), (5, 4, 3), (5, 4, 4), (5, 4, 5), (5, 5, 1), (5, 5, 2), (5, 5, 3), (5, 5, 4), (5, 5, 5)]
Traceback (most recent call last):
  File "main.py", line 61, in <module>
    main(args)
  File "main.py", line 43, in main
    envs = make_vec_envs(args, './logs/runinfo', True)
  File "/home/steven/Online-3D-BPP-PCT-main/envs.py", line 107, in make_vec_envs
    spaces = [env.observation_space, env.action_space]
  File "/home/steven/anaconda3/envs/bpp/lib/python3.7/site-packages/gym/core.py", line 229, in __getattr__
    return getattr(self.env, name)
AttributeError: 'PackingDiscrete' object has no attribute 'action_space'

My Envs: Python == 3.7.13, pytorch == 1.10.1, gym == 0.23.1,  Ubuntu 18.04

Thanks!

**Comment by luzhenyv** [comment]
I created a new conda environment Python == 3.7.7, pytorch == 1.10.1, gym == 0.15.7, Ubuntu 18.04, like [https://github.com/alexfrom0815/Online-3D-BPP-PCT/issues/3](https://github.com/alexfrom0815/Online-3D-BPP-PCT/issues/3) . I solved it. Thank you.
